---
- hosts: localhost
  gather_facts: false
  connection: local

  vars:
    - object: Pink Floyd
    - condition: comfortably numb
    - temp_file_field: present

  tasks:
    - name: This is an ansible module written in Python
      custompython:
        object: "{{ object }}"
        condition: "{{ condition }}"
        tempfile: "{{ temp_file_bool }}"
      register: modoutput
      ignore_errors: true

    - debug:
        var: modoutput

